/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 animal.gltf 
Author: Ian Christopher (https://sketchfab.com/ianchrisjohn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dugong-sea-cow-17bdf341fcc047888935f67a05dd2fea
Title: Dugong (Sea Cow)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/animal.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.357, -2.946, -2.215]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials["null"]}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["null"]}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["null"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animal.gltf");
